-- =====================================================================
-- 0016_mode_spell — 題型 enum 補上 'spell'
--
-- 【為什麼會漏】
--   新增一個題型要動四個地方：
--     ① shared/js/study/modes/<id>.js      題型本身
--     ② shared/js/study/modes/index.js     註冊進 ALL
--     ③ 題型選單                            —— 已改成由註冊表產生，不必再動
--     ④ 資料庫的 study_mode_kind enum       ← 漏掉的是這個
--
--   前三個在本機都測得到，第四個不會 ——
--   單元測試用的是替身，不驗 enum；而稽核當時只查資料內容，不查寫入。
--   使用者選了「拼出來」，得到「儲存失敗：invalid input value for
--   enum study_mode_kind」才發現。
--
-- 【影響範圍比「存不了偏好」更大】
--   reviews.mode 與 study_sessions.mode 都是這個 enum，
--   所以用「拼出來」答的每一題都寫不進去 ——
--   答了半天，記錄是空的、排程也不會前進。
--
-- 【為什麼不把 mode 改成 text】
--   enum 的價值就是「寫錯的值進不來」。這次它正是這樣擋住的 ——
--   擋的是我漏了一步，不是它太嚴格。
--   改成 text 會讓下次拼錯字（'spel'）默默寫進去，那才是真的難查。
-- =====================================================================

alter type public.study_mode_kind add value if not exists 'spell';
